service: frisky-girl-farm-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'prod'}
  region: us-west-2
  timeout: 30
  # This will become the default in serverless v3, and can be removed at that
  # point
  lambdaHashingVersion: 20201221
  environment:
    GOOGLE_SPREADSHEET_ID: ${file(config.${self:provider.stage}.json):spreadsheet_id}
    GOOGLE_CONFIG: ${file(config.${self:provider.stage}.json)}
    REGION:
      Ref: AWS::Region
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:SendBulkTemplatedEmail'
          Resource: '*'

functions:
  app:
    handler: app.server

    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-plugin-monorepo
  - '@haftahave/serverless-ses-template'
  - '@connected-home/serverless-plugin-stringify-variables'

custom:
  sesTemplates:
    configFile: ./ses-email-templates/index.js
