name: CI

on:
  push:
    branches: '*'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}      

      - run: yarn install --frozen-lockfile
      - run: yarn lint

      - name: Test backend
        run: yarn test
        working-directory: packages/frisky-girl-farm-api

      - name: Test frontend
        run: yarn test
        working-directory: packages/frisky-girl-farm

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}      

      - run: yarn install --frozen-lockfile

      - name: Deploy admin
        run: echo ${{secrets.CLASP_OAUTH_CREDENTIALS}} | base64 -d > ~/.clasprc.json && yarn deploy
        working-directory: packages/frisky-girl-farm-admin
        timeout-minutes: 1

      - name: Deploy backend
        run: echo ${{secrets.GOOGLE_SHEETS_CONFIG}} | base64 -d > config.prod.json && yarn deploy
        working-directory: packages/frisky-girl-farm-api

      - name: Deploy frontend
        run: yarn deploy --activate production
        working-directory: packages/frisky-girl-farm
